### ISSUE TITLE
About the trained model

### ISSUE THREAD

**Issue by xingchenzhang** [HaoZhang1018/MFF-GAN#1]
Hi,

Thank you very much for your nice work. I have a question about the trained model you provide. Is this model trained on Lytro dataset or on MFI-WHU model? Could you also explain which images you used for training? In the paper, you mentioned that 10 in Lytro and 30 in MFI-WHU were used for testing. However, we do not know which 10 and which 30 were used for testing.

Thanks a lot!
Xingchen

**Comment by HaoZhang1018** [comment]
> Hi,
> 
> Thank you very much for your nice work. I have a question about the trained model you provide. Is this model trained on Lytro dataset or on MFI-WHU model? Could you also explain which images you used for training? In the paper, you mentioned that 10 in Lytro and 30 in MFI-WHU were used for testing. However, we do not know which 10 and which 30 were used for testing.
> 
> Thanks a lot!
> Xingchen
We update the pre-trained models provided and indicated on which dataset they were trained.  As for the images used for testing, please refer to the attachment.
[Test_data_MFF-GAN.zip](https://github.com/HaoZhang1018/MFF-GAN/files/5627332/Test_data_MFF-GAN.zip)

**Comment by xingchenzhang** [comment]
@HaoZhang1018 

Thank you very much for this. Now it is clear.

Bests,
Xingchen
