### ISSUE TITLE
Software requirements information is needed.

### ISSUE THREAD

**Issue by 19nm5a0403** [HaoZhang1018/MFF-GAN#3]
Hello Mr. HaoZhang,
We are working on a project called MFF GAN, we tried to access your code but our major study is ECE(Electronics)  we don't have sufficient knowledge on programming, so kindly specify the software which has to be installed and provide detailed processing steps to run your code. 
As we are using windows 8,10 operating system and installed python version 3.6,3.8 in that OS, so provide the software packages which are compatible to the mentioned versions.
Kindly please go through this issue and help us to solve our project.

Thankyou sir.

**Comment by HaoZhang1018** [comment]
> Hello Mr. HaoZhang, We are working on a project called MFF GAN, we tried to access your code but our major study is ECE(Electronics) we don't have sufficient knowledge on programming, so kindly specify the software which has to be installed and provide detailed processing steps to run your code. As we are using windows 8,10 operating system and installed python version 3.6,3.8 in that OS, so provide the software packages which are compatible to the mentioned versions. Kindly please go through this issue and help us to solve our project.
> 
> Thankyou sir.

Hello. We have updated the "README.md" to add the dependency packages needed to run the code of the MMF-GAN. At first, you are advised to install the anaconda tool. Then, you could use "conda create -n your_env_name python=2.7" to create a new  environment for running. Subsequently, you could use "conda  install  xxx=n.n" to install the required packages that are provided in the README.md, e.g., "conda  install  tensorflow-gpu = 1.9.0". Finally, activate your created environment by "conda activate your_env_name", and run the code according to "CUDA_VISIBLE_DEVICES=0 python main.py".

**Comment by 19nm5a0403** [comment]
Thankyou for your time sir ,this information is very valuable to us. Sent from Mail for Windows From: Hao ZhangSent: 03 May 2022 17:59To: HaoZhang1018/MFF-GANCc: 19nm5a0403; AuthorSubject: Re: [HaoZhang1018/MFF-GAN] Software requirements information is needed. (Issue #3) Hello Mr. HaoZhang, We are working on a project called MFF GAN, we tried to access your code but our major study is ECE(Electronics) we don't have sufficient knowledge on programming, so kindly specify the software which has to be installed and provide detailed processing steps to run your code. As we are using windows 8,10 operating system and installed python version 3.6,3.8 in that OS, so provide the software packages which are compatible to the mentioned versions. Kindly please go through this issue and help us to solve our project.Thankyou sir.Hello. We have updated the "README.md" to add the dependency packages needed to run the code of the MMF-GAN. At first, you are advised to install the anaconda tool. Then, you could use "conda create -n your_env_name python=2.7" to create a new environment for running. Subsequently, you could use "conda install xxx=n.n" to install the required packages that are provided in the README.md, e.g., "conda install tensorflow-gpu = 1.9.0". Finally, activate your created environment by "conda activate your_env_name", and run the code according to "CUDA_VISIBLE_DEVICES=0 python main.py".—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
